const students = [
  {
    _id: '5b21ca3eeb7f6fbccd471815',
    first_name: 'Aaron',
    last_name: 'Nichols',
    email: 'aaron_nichols@codesmithr.com',
    number_of_books_read: 12,
    number_of_logs_submitted: 11,
    school: 'Southwest Dekalb High School',
    grade: 11,
    favorite_Book: 'THE LAST THING HE TOLD ME',
    currently_reading: 'ONCE THERE WERE WOLVES',
    log: '',
    image:
      'https://images.unsplash.com/photo-1554126807-6b10f6f6692a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471816',
    first_name: 'Abigail',
    last_name: 'Winters',
    email: 'abigail_winters@codesmithr.com',
    number_of_books_read: 8,
    number_of_logs_submitted: 15,
    school: 'McNair High School',
    grade: 11,
    favorite_Book: 'THE CELLIST',
    currently_reading: 'AFTERPARTIES',
    log: '',
    image:
      'https://images.unsplash.com/photo-1616024900828-58ec58694cd6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471817',
    first_name: 'Beauden',
    last_name: 'Calderon',
    email: 'beauden_calderon@codesmith.com',
    number_of_books_read: 7,
    number_of_logs_submitted: 7,
    school: 'Cedar Grove High School',
    grade: 12,
    favorite_Book: 'THE PAPER PALACE',
    currently_reading: 'THE LAST THING HE TOLD ME',
    log: '',
    image:
      'https://images.unsplash.com/photo-1531311243148-d2653fa84700?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471818',
    first_name: 'Elysha',
    last_name: 'Crane',
    email: 'elysha_crane@codesmith.com',
    number_of_books_read: 15,
    number_of_logs_submitted: 15,
    school: 'Douglas High School',
    grade: 12,
    favorite_Book: 'BILLY SUMMERS',
    currently_reading: 'WE WERE NEVER HERE',
    log: '',
    image:
      'https://images.unsplash.com/photo-1547727272-123a2ffe7148?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=666&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471819',
    first_name: 'Wallace',
    last_name: 'Quinn',
    email: 'wallace_quinn@codesmith.com',
    number_of_books_read: 14,
    number_of_logs_submitted: 14,
    school: 'Stephenson Experimental School',
    grade: 11,
    favorite_Book: 'BLACK ICE',
    currently_reading: 'BLIND TIGER',
    log: '',
    image:
      'https://images.unsplash.com/photo-1596496638503-0980ae36f17a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471820',
    first_name: 'Peter',
    last_name: 'Hope',
    email: 'peter_hope@codesmith.com',
    number_of_books_read: 9,
    number_of_logs_submitted: 9,
    school: 'Towers High School',
    grade: 12,
    favorite_Book: 'THE MAIDENS',
    currently_reading: 'THE MIDNIGHT LIBRARY',
    log: '',
    image:
      'https://images.unsplash.com/photo-1556216009-b4503ebd4ccf?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471821',
    first_name: 'Conan',
    last_name: 'Dallas',
    email: 'conan_dallas@codesmith.com',
    number_of_books_read: 4,
    number_of_logs_submitted: 4,
    school: 'PS-13 High School',
    grade: 12,
    favorite_Book: 'MALIBU RISING',
    currently_reading: 'THE TURNOUT',
    log: '',
    image:
      'https://images.unsplash.com/photo-1503521010279-dbf437e68b79?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=668&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471822',
    first_name: 'Alice',
    last_name: 'Lou',
    email: 'avery_kennedy@codesmith.com',
    number_of_books_read: 13,
    number_of_logs_submitted: 13,
    school: 'American High School of Beijing',
    grade: 10,
    favorite_Book: "THE PRESIDENT'S DAUGHTER",
    currently_reading: 'WE ARE THE BRENNANS',
    log: '',
    image:
      'https://images.unsplash.com/photo-1619253690419-4e3a7753c246?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471823',
    first_name: 'Piper',
    last_name: 'Rawling',
    email: 'piper_rawlings@codesmith.com',
    number_of_books_read: 14,
    number_of_logs_submitted: 14,
    school: 'Malcolm Little Magnet School',
    grade: 11,
    favorite_Book: 'NOT A HAPPY FAMILY',
    currently_reading: 'THE PAPER PALACE',
    log: '',
    image:
      'https://images.unsplash.com/photo-1585435628319-cbbbf55be9df?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1038&q=80',
  },
  {
    _id: '5b21ca3eeb7f6fbccd471824',
    first_name: 'Ralph',
    last_name: 'Smith',
    email: 'codesmithr@outlook.com',
    number_of_books_read: 15,
    number_of_logs_submitted: 15,
    school: 'Columbia High School',
    grade: 12,
    favorite_Book: 'THE MIDNIGHT LIBRARY',
    currently_reading: '',
    log: '',
    image:
      'https://images.unsplash.com/photo-1519689373023-dd07c7988603?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80',
  },
];

/* const favoriteBook = books[(books.title * Math.random()) | 0]; */

export function getStudents() {
  return students;
}
